# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  ds-utils-benchmarks:
    dependencies:
    - base
    - ds-utils
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: ds-utils is a new Haskeleton package.
executables:
  ds-utils:
    dependencies:
    - base
    - ds-utils
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: githubuser/ds-utils
library:
  dependencies:
  - base
  source-dirs: library
license: MIT
maintainer: Author name here
name: ds-utils
synopsis: A new Haskeleton package.
tests:
  ds-utils-test-suite:
    dependencies:
    - base
    - ds-utils
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
